import XCTest
@testable import ProductStudioPro

final class CatalogLogicTests: XCTestCase {

    // MARK: - BarcodeCanonicalForm

    func testUPCACheckDigitValid() {
        // Classic UPC-A for Coca-Cola 12oz (example GTIN with valid check digit)
        XCTAssertTrue(BarcodeCanonicalForm.isValidGTINCheckDigit("049000028911"))
        XCTAssertFalse(BarcodeCanonicalForm.isValidGTINCheckDigit("049000028910"))
    }

    func testEAN13LeadingZeroMapsToUPCALabelDigits() {
        let ean = "0049000028911"
        XCTAssertTrue(BarcodeCanonicalForm.isValidGTINCheckDigit(ean))
        let label = BarcodeCanonicalForm.labelDigits(from: ean)
        XCTAssertEqual(label, "049000028911")
    }

    func testCanonicalProductCodeRejectsBadLength() {
        XCTAssertNil(BarcodeCanonicalForm.canonicalProductCode(from: "12345"))
        XCTAssertNil(BarcodeCanonicalForm.canonicalProductCode(from: "ABCDEF"))
    }

    func testNormalizeForStorageKeepsAlphaSKUWithoutDigits() {
        let sku = "SKU-RED"
        XCTAssertEqual(BarcodeCanonicalForm.normalizeForStorage(sku), sku)
    }

    func testNormalizeForStorageExtractsDigitsFromMixedSKU() {
        // When digits are present but not a valid GTIN length, storage keeps digits only.
        XCTAssertEqual(BarcodeCanonicalForm.normalizeForStorage("SKU-RED-42"), "42")
    }

    // MARK: - FileNameRules

    func testStrictJPGNameStripsExtensionsAndUnsafeChars() {
        let name = FileNameRules.strictJPGName(
            baseName: "My Product!!!.jpg",
            angle: .none,
            duplicateCopyIndex: 1
        )
        XCTAssertTrue(name.hasSuffix(".jpg"))
        XCTAssertFalse(name.lowercased().contains(".jpg.jpg"))
        XCTAssertFalse(name.contains(" "))
        XCTAssertFalse(name.contains("!"))
    }

    func testStrictImageNameAddsCopyAndAngleSuffix() {
        let name = FileNameRules.strictImageName(
            baseName: "049000028911",
            angle: .front,
            duplicateCopyIndex: 2,
            format: .png,
            multiAngleOrdinal: 0
        )
        XCTAssertEqual(name, "049000028911-front-copy2.png")
    }

    func testMultiAngleOrdinalOverridesAngleSuffix() {
        let name = FileNameRules.strictJPGName(
            baseName: "049000028911",
            angle: .front,
            duplicateCopyIndex: 1,
            multiAngleOrdinal: 3
        )
        XCTAssertEqual(name, "049000028911-3.jpg")
    }

    func testCaptureLabelCanonicalizesValidUPC() {
        let label = FileNameRules.captureLabel(from: " 0049000028911 ")
        XCTAssertEqual(label, "049000028911")
    }

    func testIsAutoGeneratedImportBaseName() {
        XCTAssertTrue(FileNameRules.isAutoGeneratedImportBaseName("IMG_20240101_120000_001"))
        XCTAssertTrue(FileNameRules.isAutoGeneratedImportBaseName("PSP_20260804_205803_739"))
        XCTAssertTrue(FileNameRules.isAutoGeneratedImportBaseName("Product-Studio-Pro_20260804_205803_739"))
        XCTAssertFalse(FileNameRules.isAutoGeneratedImportBaseName("049000028911"))
    }

    func testRandomNativeNameUsesShortPrefix() {
        let name = FileNameRules.randomNativeName()
        XCTAssertTrue(name.hasPrefix("PSP_"))
        XCTAssertFalse(name.hasPrefix("Product-Studio-Pro_"))
    }

    // MARK: - ExportPhotoFilter migration

    func testResolvedFilterMapsLegacyAliases() {
        XCTAssertEqual(ExportPhotoFilter.resolved(from: "Vivid Warm"), .warmLuxury)
        XCTAssertEqual(ExportPhotoFilter.resolved(from: "Technicolor"), .photosVibrant)
        XCTAssertEqual(ExportPhotoFilter.resolved(from: "Autocorrect"), .auto)
        XCTAssertEqual(ExportPhotoFilter.resolved(from: nil), .none)
        XCTAssertEqual(ExportPhotoFilter.resolved(from: ""), .none)
    }

    func testResolvedFilterKeepsCurrentRawValues() {
        XCTAssertEqual(ExportPhotoFilter.resolved(from: ExportPhotoFilter.jewelryShine.rawValue), .jewelryShine)
        XCTAssertEqual(ExportPhotoFilter.resolved(from: "Unknown Filter XYZ"), .none)
    }

    // MARK: - BackgroundFillSpec decode

    func testBackgroundFillSpecRoundTrip() throws {
        let original = BackgroundFillSpec.catalogWhite
        let data = try XCTUnwrap(original.encodedData())
        let decoded = try XCTUnwrap(BackgroundFillSpec.decoded(from: data))
        XCTAssertEqual(decoded.fillKind, original.fillKind)
        XCTAssertEqual(decoded.colorHexes, original.colorHexes)
    }

    func testBackgroundFillSpecDecodedNilForGarbage() {
        let junk = Data("not-json".utf8)
        XCTAssertNil(BackgroundFillSpec.decoded(from: junk))
        XCTAssertNil(BackgroundFillSpec.decoded(from: nil))
    }

    // MARK: - Session soft cap

    func testSoftQueueCapConstant() {
        XCTAssertEqual(CaptureSessionStore.CatalogSessionLimits.softQueueCap, 200)
        XCTAssertEqual(CaptureSessionStore.CatalogSessionLimits.maxPhotosPickerSelection, 100)
        XCTAssertEqual(CaptureSessionStore.CatalogSessionLimits.importConcurrency, 3)
    }

    // MARK: - Synthetic test images

    private func makeSyntheticTestImage(
        width: Int,
        height: Int,
        background: UIColor,
        subject: CGRect,
        subjectColor: UIColor
    ) -> UIImage {
        let size = CGSize(width: width, height: height)
        let format = UIGraphicsImageRendererFormat()
        format.scale = 1
        format.opaque = true
        let renderer = UIGraphicsImageRenderer(size: size, format: format)
        return renderer.image { ctx in
            background.setFill()
            ctx.fill(CGRect(origin: .zero, size: size))
            subjectColor.setFill()
            ctx.fill(subject)
        }
    }

    func testAIPolishEngineReturnsImageForPreCompositePass() {
        let image = makeSyntheticTestImage(
            width: 640,
            height: 640,
            background: UIColor(white: 0.92, alpha: 1),
            subject: CGRect(x: 160, y: 160, width: 320, height: 320),
            subjectColor: UIColor(white: 0.35, alpha: 1)
        )
        let enhanced = AIPolishEngine.enhance(image, pass: .preComposite)
        XCTAssertNotEqual(enhanced.size, .zero)
        guard let cg = enhanced.cgImage else {
            XCTFail("Expected CGImage output")
            return
        }
        XCTAssertGreaterThan(cg.width, 0)
        XCTAssertGreaterThan(cg.height, 0)
    }

    func testAIPolishEnginePostCompositeIsLightTouch() {
        let image = makeSyntheticTestImage(
            width: 400,
            height: 400,
            background: .white,
            subject: CGRect(x: 100, y: 100, width: 200, height: 200),
            subjectColor: UIColor(white: 0.4, alpha: 1)
        )
        let enhanced = AIPolishEngine.enhance(image, pass: .postComposite)
        XCTAssertEqual(enhanced.size.width, image.size.width, accuracy: 1)
    }

    func testSoftSyntheticShadowSettingsClampsValues() {
        let raw = SoftSyntheticShadowSettings(isEnabled: true, opacity: 2.0, blur: 80)
        let clamped = raw.clamped()
        XCTAssertEqual(clamped.opacity, 1.0, accuracy: 0.001)
        XCTAssertEqual(clamped.blur, 48.0, accuracy: 0.001)
    }

    func testSoftSyntheticShadowPerspectiveScalesWithAspect() {
        let tall = SoftSyntheticShadowEngine.perspectiveMetrics(for: CGRect(x: 0, y: 0, width: 300, height: 600))
        let wide = SoftSyntheticShadowEngine.perspectiveMetrics(for: CGRect(x: 0, y: 0, width: 600, height: 300))
        XCTAssertGreaterThan(wide.widthScale, tall.widthScale)
        XCTAssertLessThan(wide.verticalSquash, tall.verticalSquash + 0.05)
    }

    func testSoftSyntheticShadowEngineDrawsOnCanvas() {
        let format = UIGraphicsImageRendererFormat.default()
        format.scale = 1
        format.opaque = false
        let cutout = UIGraphicsImageRenderer(size: CGSize(width: 120, height: 160), format: format).image { ctx in
            UIColor.clear.setFill()
            ctx.fill(CGRect(x: 0, y: 0, width: 120, height: 160))
            UIColor(white: 0.2, alpha: 1).setFill()
            ctx.fill(CGRect(x: 20, y: 20, width: 80, height: 120))
        }
        let canvas = CGSize(width: 400, height: 400)
        let productRect = CGRect(x: 140, y: 80, width: 120, height: 160)
        let composed = UIGraphicsImageRenderer(size: canvas, format: format).image { ctx in
            UIColor.white.setFill()
            ctx.fill(CGRect(origin: .zero, size: canvas))
            SoftSyntheticShadowEngine.draw(
                in: ctx.cgContext,
                cutout: cutout,
                productRect: productRect,
                canvasSize: canvas,
                rotationDegrees: 0,
                flipHorizontal: false,
                flipVertical: false,
                settings: .studioDefault
            )
        }
        XCTAssertEqual(composed.size, canvas)
    }

    func testCSVExporterIncludesLegacyAndExtendedColumns() {
        let product = makeSyntheticTestImage(
            width: 800,
            height: 800,
            background: .white,
            subject: CGRect(x: 200, y: 200, width: 400, height: 400),
            subjectColor: UIColor(white: 0.2, alpha: 1)
        )
        let captured = CapturedProduct(
            sequence: 1,
            upc: "012345678905",
            angle: .front,
            image: product,
            originalImage: product,
            backgroundRemoved: true,
            polishEnabled: true,
            canvasWidth: 800,
            canvasHeight: 800
        )
        let row = CSVExportRowContext(
            product: captured,
            namingMode: .scannedUPC,
            format: .jpg,
            archivePath: "Images/\(captured.filename(for: .scannedUPC, format: .jpg))",
            byteCount: 120_000,
            exportWidth: 800,
            exportHeight: 800,
            marketplaceProfile: .amazon,
            brandName: "Acme",
            exportDate: Date(timeIntervalSince1970: 1_700_000_000)
        )
        guard let data = CSVExporter.csvData(rows: [row]) else {
            XCTFail("Expected CSV data")
            return
        }
        let text = String(decoding: data, as: UTF8.self)
        XCTAssertTrue(text.contains("sequence"))
        XCTAssertTrue(text.contains("filename"))
        XCTAssertTrue(text.contains("SKU"))
        XCTAssertTrue(text.contains("Shadow Applied"))
        XCTAssertTrue(text.contains("012345678905"))
    }

    func testManifestGeneratorEncodesProjectMetadata() {
        let product = CapturedProduct(
            sequence: 1,
            upc: "SKU-1",
            angle: .front,
            image: UIImage(),
            originalImage: UIImage(),
            backgroundRemoved: true,
            polishEnabled: true,
            studioShadow: .studioDefault
        )
        let manifest = ManifestGenerator.generate(
            projectName: "Summer Launch",
            profile: .profile(for: .shopify),
            products: [product]
        )
        XCTAssertEqual(manifest.projectName, "Summer Launch")
        XCTAssertEqual(manifest.marketplace, "Shopify")
        XCTAssertEqual(manifest.imageCount, 1)
        XCTAssertTrue(manifest.shadowEnabled)
        guard let data = ManifestGenerator.jsonData(for: manifest),
              let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            XCTFail("Expected manifest JSON")
            return
        }
        XCTAssertEqual(json["csvFilename"] as? String, "products.csv")
        XCTAssertEqual(json["imagesFolder"] as? String, "Images")
    }

    func testZipExporterBuildsFolderStructure() {
        let entries = [
            ZipExporter.Entry(archivePath: "Images/Product001.jpg", data: Data([0xFF, 0xD8])),
            ZipExporter.Entry(archivePath: "products.csv", data: Data("a,b\r\n".utf8)),
            ZipExporter.Entry(archivePath: "manifest.json", data: Data("{}".utf8)),
        ]
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("ExportPackageTest.zip")
        defer { try? FileManager.default.removeItem(at: url) }
        XCTAssertTrue(ZipExporter.makePackageZip(entries: entries, zipDestination: url))
        XCTAssertTrue(FileManager.default.fileExists(atPath: url.path))
    }

    // MARK: - Product metadata

    func testMetadataMigratorCreatesProductFromCapturedItem() {
        let image = makeSyntheticTestImage(
            width: 800,
            height: 800,
            background: .white,
            subject: CGRect(x: 200, y: 200, width: 400, height: 400),
            subjectColor: UIColor(white: 0.2, alpha: 1)
        )
        let captured = CapturedProduct(
            sequence: 3,
            upc: "012345678905",
            angle: .front,
            image: image,
            originalImage: image,
            capturedAt: Date(timeIntervalSince1970: 1_700_000_000),
            backgroundRemoved: true,
            polishEnabled: true,
            canvasWidth: 800,
            canvasHeight: 800
        )
        let sessionID = UUID()
        let bundle = MetadataMigrator.migrateFromLegacy(
            sessionID: sessionID,
            sessionName: "Test Session",
            capturedProducts: [captured],
            brandName: "Acme",
            marketplace: "Amazon"
        )
        XCTAssertEqual(bundle.project.id, sessionID)
        XCTAssertEqual(bundle.project.projectName, "Test Session")
        XCTAssertEqual(bundle.products.count, 1)
        XCTAssertEqual(bundle.imageAssets.count, 1)
        XCTAssertEqual(bundle.imageAssets[0].id, captured.id)
        XCTAssertEqual(bundle.products[0].metadata.sku, "012345678905")
        XCTAssertEqual(bundle.products[0].metadata.brand, "Acme")
        XCTAssertEqual(bundle.products[0].metadata.marketplace, "Amazon")
        XCTAssertEqual(bundle.imageAssets[0].metadata.sequence, 3)
        XCTAssertEqual(bundle.imageAssets[0].metadata.backgroundRemoved, true)
    }

    func testCSVExporterUsesMetadataWhenPresent() {
        let image = makeSyntheticTestImage(
            width: 800,
            height: 800,
            background: .white,
            subject: CGRect(x: 200, y: 200, width: 400, height: 400),
            subjectColor: UIColor(white: 0.2, alpha: 1)
        )
        let captured = CapturedProduct(
            sequence: 1,
            upc: "012345678905",
            angle: .front,
            image: image,
            originalImage: image,
            backgroundRemoved: true,
            polishEnabled: true,
            canvasWidth: 800,
            canvasHeight: 800
        )
        let productMeta = ProductMetadata(
            sku: "012345678905",
            barcode: "012345678905",
            productName: "Test Product",
            brand: "Acme",
            category: "Beverages",
            marketplace: "Amazon"
        )
        let imageMeta = MetadataMigrator.buildImageMetadata(from: captured, existing: nil, fileSize: 50_000)
        let row = CSVExportRowContext(
            product: captured,
            namingMode: .scannedUPC,
            format: .jpg,
            archivePath: "Images/012345678905-front.jpg",
            byteCount: 50_000,
            exportWidth: 800,
            exportHeight: 800,
            marketplaceProfile: .amazon,
            brandName: "Acme",
            exportDate: Date(timeIntervalSince1970: 1_700_000_000),
            productMetadata: productMeta,
            imageMetadata: imageMeta
        )
        guard let data = CSVExporter.csvData(rows: [row]) else {
            XCTFail("Expected CSV data")
            return
        }
        let text = String(decoding: data, as: UTF8.self)
        XCTAssertTrue(text.contains("Beverages"))
        XCTAssertTrue(text.contains("Test Product"))
        XCTAssertTrue(text.contains("Amazon"))
    }

    func testSessionMetadataBundleRoundTrip() throws {
        let sessionID = UUID()
        let productMeta = ProductMetadata(sku: "SKU-1", productName: "Widget")
        let product = Product(id: UUID(), metadata: productMeta, imageAssetIDs: [UUID()])
        let imageAsset = ImageAsset(
            id: product.imageAssetIDs[0],
            productID: product.id,
            metadata: ImageMetadata(filename: "Widget.jpg", width: 1000, height: 1000)
        )
        let bundle = SessionMetadataBundle(
            project: ProjectMetadata(id: sessionID, projectName: "Launch"),
            products: [product],
            imageAssets: [imageAsset]
        )
        let data = try XCTUnwrap(try? JSONEncoder().encode(bundle))
        let decoded = try XCTUnwrap(try? JSONDecoder().decode(SessionMetadataBundle.self, from: data))
        XCTAssertEqual(decoded.project.projectName, "Launch")
        XCTAssertEqual(decoded.products.count, 1)
        XCTAssertEqual(decoded.imageAssets.count, 1)
    }
}
