import XCTest
@testable import ProductStudioPro

final class CatalogLogicTests: XCTestCase {

    // MARK: - BarcodeCanonicalForm

    func testUPCACheckDigitValid() {
        // Classic UPC-A for Coca-Cola 12oz (example GTIN with valid check digit)
        XCTAssertTrue(BarcodeCanonicalForm.isValidGTINCheckDigit("049000028911"))
        XCTAssertFalse(BarcodeCanonicalForm.isValidGTINCheckDigit("049000028910"))
    }

    func testEAN13LeadingZeroMapsToUPCALabelDigits() {
        let ean = "0049000028911"
        XCTAssertTrue(BarcodeCanonicalForm.isValidGTINCheckDigit(ean))
        let label = BarcodeCanonicalForm.labelDigits(from: ean)
        XCTAssertEqual(label, "049000028911")
    }

    func testCanonicalProductCodeRejectsBadLength() {
        XCTAssertNil(BarcodeCanonicalForm.canonicalProductCode(from: "12345"))
        XCTAssertNil(BarcodeCanonicalForm.canonicalProductCode(from: "ABCDEF"))
    }

    func testNormalizeForStorageKeepsAlphaSKUWithoutDigits() {
        let sku = "SKU-RED"
        XCTAssertEqual(BarcodeCanonicalForm.normalizeForStorage(sku), sku)
    }

    func testNormalizeForStorageExtractsDigitsFromMixedSKU() {
        // When digits are present but not a valid GTIN length, storage keeps digits only.
        XCTAssertEqual(BarcodeCanonicalForm.normalizeForStorage("SKU-RED-42"), "42")
    }

    // MARK: - FileNameRules

    func testStrictJPGNameStripsExtensionsAndUnsafeChars() {
        let name = FileNameRules.strictJPGName(
            baseName: "My Product!!!.jpg",
            angle: .none,
            duplicateCopyIndex: 1
        )
        XCTAssertTrue(name.hasSuffix(".jpg"))
        XCTAssertFalse(name.lowercased().contains(".jpg.jpg"))
        XCTAssertFalse(name.contains(" "))
        XCTAssertFalse(name.contains("!"))
    }

    func testStrictImageNameAddsCopyAndAngleSuffix() {
        let name = FileNameRules.strictImageName(
            baseName: "049000028911",
            angle: .front,
            duplicateCopyIndex: 2,
            format: .png,
            multiAngleOrdinal: 0
        )
        XCTAssertEqual(name, "049000028911-front-copy2.png")
    }

    func testMultiAngleOrdinalOverridesAngleSuffix() {
        let name = FileNameRules.strictJPGName(
            baseName: "049000028911",
            angle: .front,
            duplicateCopyIndex: 1,
            multiAngleOrdinal: 3
        )
        XCTAssertEqual(name, "049000028911-3.jpg")
    }

    func testCaptureLabelCanonicalizesValidUPC() {
        let label = FileNameRules.captureLabel(from: " 0049000028911 ")
        XCTAssertEqual(label, "049000028911")
    }

    func testIsAutoGeneratedImportBaseName() {
        XCTAssertTrue(FileNameRules.isAutoGeneratedImportBaseName("IMG_20240101_120000_001"))
        XCTAssertFalse(FileNameRules.isAutoGeneratedImportBaseName("049000028911"))
    }

    // MARK: - ExportPhotoFilter migration

    func testResolvedFilterMapsLegacyAliases() {
        XCTAssertEqual(ExportPhotoFilter.resolved(from: "Vivid Warm"), .warmLuxury)
        XCTAssertEqual(ExportPhotoFilter.resolved(from: "Technicolor"), .photosVibrant)
        XCTAssertEqual(ExportPhotoFilter.resolved(from: "Autocorrect"), .auto)
        XCTAssertEqual(ExportPhotoFilter.resolved(from: nil), .none)
        XCTAssertEqual(ExportPhotoFilter.resolved(from: ""), .none)
    }

    func testResolvedFilterKeepsCurrentRawValues() {
        XCTAssertEqual(ExportPhotoFilter.resolved(from: ExportPhotoFilter.jewelryShine.rawValue), .jewelryShine)
        XCTAssertEqual(ExportPhotoFilter.resolved(from: "Unknown Filter XYZ"), .none)
    }

    // MARK: - BackgroundFillSpec decode

    func testBackgroundFillSpecRoundTrip() throws {
        let original = BackgroundFillSpec.catalogWhite
        let data = try XCTUnwrap(original.encodedData())
        let decoded = try XCTUnwrap(BackgroundFillSpec.decoded(from: data))
        XCTAssertEqual(decoded.fillKind, original.fillKind)
        XCTAssertEqual(decoded.colorHexes, original.colorHexes)
    }

    func testBackgroundFillSpecDecodedNilForGarbage() {
        let junk = Data("not-json".utf8)
        XCTAssertNil(BackgroundFillSpec.decoded(from: junk))
        XCTAssertNil(BackgroundFillSpec.decoded(from: nil))
    }

    // MARK: - Session soft cap

    func testSoftQueueCapConstant() {
        XCTAssertEqual(CaptureSessionStore.CatalogSessionLimits.softQueueCap, 200)
        XCTAssertEqual(CaptureSessionStore.CatalogSessionLimits.maxPhotosPickerSelection, 100)
        XCTAssertEqual(CaptureSessionStore.CatalogSessionLimits.importConcurrency, 3)
    }
}
