#!/usr/bin/env python3
"""Generates ProductStudioPro/GradientPresetCatalog.swift from gradient_catalog_30_groups.py."""
from pathlib import Path

from gradient_catalog_30_groups import GROUPS


def slug_preset(name: str) -> str:
    out = []
    for ch in name.lower():
        if ch.isalnum():
            out.append(ch)
        elif ch in " -_&/":
            if out and out[-1] != "-":
                out.append("-")
    s = "".join(out).strip("-")
    while "--" in s:
        s = s.replace("--", "-")
    return s or "preset"


def swift_hex_array(hexes: list[str]) -> str:
    inner = ", ".join(f'"{h}"' for h in hexes)
    return f"[{inner}]"


def main() -> None:
    out = Path(__file__).resolve().parents[1] / "ProductStudioPro" / "GradientPresetCatalog.swift"
    lines = [
        "// Generated by scripts/generate_gradient_catalog.py — do not edit by hand.",
        "// Default per preset: Linear, bottomTrailing, 135° (catalogPreset).",
        "import Foundation",
        "",
        "enum GradientPresetCatalog {",
        "    static let extendedGroups: [GradientPresetGroup] = [",
    ]
    for gid, title, presets in GROUPS:
        lines.append(f'        GradientPresetGroup(id: "{gid}", title: "{title}", presets: [')
        for name, hexes in presets:
            pid = f"{gid}-{slug_preset(name)}"
            lines.append(
                f'            GradientPresetGroupLibrary.catalogPreset("{pid}", "{name}", {swift_hex_array(hexes)}),'
            )
        lines.append("        ]),")
    lines.append("    ]")
    lines.append("}")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out} ({len(GROUPS)} groups)")


if __name__ == "__main__":
    main()
